version: 0.2
env:
  secrets-manager:
    DOCKER_KEY: /dockerhub/credentials/password
    DOCKER_USER: /dockerhub/credential/username

phases: 
  build:
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t sabiut/node-server ."
      - "docker tag sabiut/node-server sabiut/node-server:latest"

  
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push sabiut/node-server:latest"
  pre_build:
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username $DOCKER_USER --password $DOCKER_KEY"
  

